### ISSUE TITLE
Неизвестная мне причина сломала телеграм бота

### ISSUE THREAD

**Issue by SpaceInMe** [PonomareVlad/telebot-vercel#1]
Непонятно, что произошло, и я не могу поставить больше вебхук.

Обновление всех библиотек через npm не помогло.

Судя по логам проблема не в моём коде.

![image](https://user-images.githubusercontent.com/33953266/225962684-362e6efd-2e46-4f1c-a676-aedc1f77c736.png)
![image](https://user-images.githubusercontent.com/33953266/225962688-22f79191-a782-44db-b851-d59b71ca90f8.png)

**Comment by PonomareVlad** [comment]
@MrFredber Благодарю за обратную связь, действительно, есть ломающее изменение в коде проекта, и после обновления на версию `1.0.0` вам нужно изменить формат передачи аргументов для некоторых методов

### Для метода `start()`

```js
start(bot) // before

start({bot}) // after
```

### Для метода `setWebhook()`
```js
setWebhook(bot, path) // before

setWebhook({bot, path}) // after
```

[Пример проекта с актуальными изменениями](https://github.com/PonomareVlad/TeleVercelBot/tree/main/api)

Сообщите пожалуйста, помогло ли вам это исправление 🙂

**Comment by SpaceInMe** [comment]
`setWebhook()` у меня уже был новый, а `start()` был старый.
Этот фикс помог, спасибо!
